-- Запрос, которым снимается db/schema/tandem_full.sql. Выполнить в боевой базе (SQL-редактор Supabase
-- или MCP execute_sql), результат (JSON-массив строк ord/kind/nm/sql) сохранить в файл и собрать:
--   node tools/build-schema-snapshot.mjs <файл-с-результатом>
with seqs as (
  select 10 as ord, 'sequence' kind, c.relname nm,
    format('create sequence if not exists tandem.%I as %s increment %s minvalue %s maxvalue %s start %s;', c.relname, format_type(s.seqtypid, null), s.seqincrement, s.seqmin, s.seqmax, s.seqstart) sql
  from pg_class c join pg_sequence s on s.seqrelid = c.oid where c.relnamespace = 'tandem'::regnamespace
    and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'i')
), tabs as (
  select 20 as ord, 'table' kind, c.relname nm,
    format(E'create table if not exists tandem.%I (\n%s\n);', c.relname,
      (select string_agg(format('  %I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
          case when a.attidentity = 'a' then ' generated always as identity' when a.attidentity = 'd' then ' generated by default as identity' else '' end,
          case when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
               when d.adbin is not null and a.attidentity = '' then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end,
          case when a.attnotnull then ' not null' else '' end), E',\n' order by a.attnum)
       from pg_attribute a left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
       where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped)) sql
  from pg_class c where c.relnamespace = 'tandem'::regnamespace and c.relkind = 'r'
), cons as (
  select case when con.contype = 'f' then 40 else 30 end as ord, 'constraint' kind, c.relname || '.' || con.conname nm,
    format('alter table tandem.%I add constraint %I %s;', c.relname, con.conname, pg_get_constraintdef(con.oid)) sql
  from pg_constraint con join pg_class c on c.oid = con.conrelid
  where c.relnamespace = 'tandem'::regnamespace and con.contype in ('p','u','c','f','x')
), idx as (
  select 35 as ord, 'index' kind, i.indexname nm, i.indexdef || ';' sql
  from pg_indexes i where i.schemaname = 'tandem'
    and not exists (select 1 from pg_constraint con join pg_class ic on ic.oid = con.conindid where ic.relname = i.indexname and ic.relnamespace = 'tandem'::regnamespace)
), seqown as (
  select 45 as ord, 'seqowner' kind, s.relname nm, format('alter sequence tandem.%I owned by tandem.%I.%I;', s.relname, t.relname, a.attname) sql
  from pg_depend d join pg_class s on s.oid = d.objid and s.relkind = 'S' join pg_class t on t.oid = d.refobjid
  join pg_attribute a on a.attrelid = t.oid and a.attnum = d.refobjsubid
  where d.deptype = 'a' and s.relnamespace = 'tandem'::regnamespace
), fns as (
  select 50 as ord, 'function' kind, p.oid::regprocedure::text nm, pg_get_functiondef(p.oid) || ';' sql
  from pg_proc p where p.prokind = 'f' and (p.pronamespace = 'tandem'::regnamespace or (p.pronamespace = 'public'::regnamespace and p.proname like 'tandem%'))
), views as (
  select 60 as ord, 'view' kind, c.relname nm, format(E'create or replace view tandem.%I as\n%s', c.relname, pg_get_viewdef(c.oid, true)) sql
  from pg_class c where c.relnamespace = 'tandem'::regnamespace and c.relkind = 'v'
), trg as (
  select 70 as ord, 'trigger' kind, t.tgname nm, pg_get_triggerdef(t.oid) || ';' sql
  from pg_trigger t join pg_class c on c.oid = t.tgrelid where c.relnamespace = 'tandem'::regnamespace and not t.tgisinternal
), rls as (
  select 80 as ord, 'rls' kind, c.relname nm, format('alter table tandem.%I enable row level security;', c.relname) sql
  from pg_class c where c.relnamespace = 'tandem'::regnamespace and c.relkind = 'r' and c.relrowsecurity
)
select ord, kind, nm, sql from (select * from seqs union all select * from tabs union all select * from cons union all select * from idx
  union all select * from seqown union all select * from fns union all select * from views union all select * from trg union all select * from rls) x
order by ord, nm;
